# Generated by Django 3.1 on 2021-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='extra_kwargs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='params',
            field=models.TextField(null=True),
        ),
    ]
